sub     esp, 0Ch
mov     ecx, [esp+0Ch+arg_4]
mov     eax, [esp+0Ch+arg_8]
fld     dword ptr [ecx]
fsub    dword ptr [eax]
fld     dword ptr [ecx+4]
fsub    dword ptr [eax+4]
fstp    [esp+0Ch+var_8]
fld     dword ptr [ecx+8]
fsub    dword ptr [eax+8]
mov     ecx, [esp+0Ch+arg_0]
fstp    [esp+0Ch+var_4]
fmul    [esp+0Ch+arg_C]
fld     [esp+0Ch+var_8]
fmul    [esp+0Ch+arg_C]
fstp    [esp+0Ch+var_8]
fld     [esp+0Ch+var_4]
fmul    [esp+0Ch+arg_C]
fstp    [esp+0Ch+var_4]
fadd    dword ptr [eax]
fstp    dword ptr [ecx]
fld     [esp+0Ch+var_8]
fadd    dword ptr [eax+4]
fstp    dword ptr [ecx+4]
fld     [esp+0Ch+var_4]
fadd    dword ptr [eax+8]
fstp    dword ptr [ecx+8]
add     esp, 0Ch
retn
