mov     eax, [esp+arg_0]
or      ecx, 0FFFFFFFFh
mov     [eax+28h], ecx
mov     [eax+20h], ecx
mov     [eax+24h], ecx
xor     ecx, ecx
mov     [eax+2Ch], ecx
mov     [eax+4Ch], ecx
mov     [eax+50h], ecx
mov     [eax+30h], ecx
mov     [eax+54h], cl
mov     [eax+58h], ecx
mov     [eax+5Ch], ecx
mov     [eax+60h], ecx
mov     [eax+64h], ecx
mov     [eax+68h], ecx
mov     [eax+70h], ecx
mov     [eax+78h], ecx
mov     [eax+74h], ecx
mov     [eax+7Ch], ecx
mov     [eax+80h], ecx
retn
