mov     eax, [esp+arg_0]
mov     eax, [eax+4]
test    eax, eax
jz      short loc_401CB5
mov     ecx, [eax+4]
test    ecx, ecx
jz      short loc_401CB5
test    eax, eax
jz      short locret_401CB7
mov     cx, [esp+arg_4]
cmp     [eax+1Ch], cx
jz      short locret_401CB7
mov     eax, [eax+4]
test    eax, eax
jz      short loc_401CB5
mov     edx, [eax+4]
test    edx, edx
jz      short loc_401CB5
test    eax, eax
jz      short locret_401CB7
jmp     short loc_401C9B
xor     eax, eax
retn
