mov     eax, [esp+arg_0]
xor     ecx, ecx
mov     [eax+18h], ecx
mov     [eax+1Ch], ecx
mov     [eax+20h], ecx
mov     [eax+24h], ecx
mov     [eax+28h], ecx
mov     [eax+2Ch], ecx
mov     [eax+30h], ecx
mov     [eax+34h], ecx
mov     [eax+38h], ecx
mov     [eax+3Ch], ecx
mov     [eax+40h], ecx
mov     [eax+44h], ecx
mov     [eax+48h], ecx
mov     [eax+4Ch], ecx
mov     [eax+50h], ecx
mov     [eax+8], ecx
mov     [eax+5Ch], ecx
mov     [eax+60h], ecx
retn
