mov     eax, [esp+arg_0]
mov     ecx, [esp+arg_4]
mov     edx, [esp+arg_8]
mov     [eax+38h], ecx
mov     ecx, [esp+arg_C]
mov     [eax+40h], ecx
mov     ecx, [esp+arg_14]
mov     [eax+3Ch], edx
mov     edx, [esp+arg_10]
mov     [eax+48h], ecx
xor     cl, cl
mov     [eax+44h], edx
mov     dl, [esp+arg_18]
mov     [eax+4Eh], cl
mov     [eax+4Dh], cl
mov     ecx, [esp+arg_1C]
mov     [eax+4Ch], dl
mov     [eax+50h], ecx
retn
