mov     eax, [esp+arg_0]
or      edx, 0FFFFFFFFh
xor     ecx, ecx
mov     [eax+0B8h], edx
mov     [eax+0BCh], edx
mov     [eax+0C0h], edx
mov     edx, 3F800000h
mov     [eax+0A0h], ecx
mov     [eax+0A8h], ecx
mov     [eax+0B0h], ecx
mov     [eax+88h], ecx
mov     [eax+90h], ecx
mov     [eax+98h], ecx
mov     [eax+0A4h], ecx
mov     [eax+0ACh], ecx
mov     [eax+0B4h], ecx
mov     [eax+8Ch], ecx
mov     [eax+94h], ecx
mov     [eax+9Ch], ecx
mov     [eax+0C4h], edx
mov     [eax+0C8h], edx
mov     [eax+0CCh], edx
mov     [eax+0D0h], ecx
mov     [eax+0D4h], edx
mov     [eax+0D8h], edx
mov     dword ptr [eax+124h], 0BF800000h
mov     [eax+0DCh], cl
mov     [eax+0DDh], cl
mov     [eax+0DFh], cl
mov     [eax+0FFh], cl
mov     [eax+128h], ecx
mov     [eax+12Ch], ecx
retn
